title: "Mon Site"
description: "Blog + portfolio avec galerie d'images."
url: "https://Marssouss.github.io" # change si domaine custom
baseurl: "" # laisser vide pour repo utilisateur. Pour repo projet: "/mon-site"

theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

author:
  name: "Ton Nom"
  email: "contact@tondomaine.com"

# SEO-tag
twitter_username: ""   # optionnel
github_username: "Marssouss"

# Build
markdown: kramdown
kramdown:
  input: GFM

# Collections par défaut
defaults:
  - scope: { path: "" }
    values:
      layout: "page"
  - scope: { path: "", type: "posts" }
    values:
      layout: "post"

minima:
  social_links:
    github: tonpseudo
  nav:
    - title: "Accueil"
      url: /
    - title: "Blog"
      url: /blog/
    - title: "Galerie"
      url: /gallery/
