title: "ABM"
description: "ABM Automatisation et BI"
url: "https://tonpseudo.github.io" # change si domaine custom
baseurl: "" # pour repo utilisateur. Pour repo projet: "/mon-site"

theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

author:
  name: "Martial BODET"
  email: "contact@tondomaine.com"

# Navigation du thème minima
minima:
  nav:
    - title: "Accueil"
      url: /
    - title: "Blog"
      url: /blog/
    - title: "Galerie"
      url: /gallery/
    - title: "Contact"
      url: /contact/ # crée la page plus tard si tu veux

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Layouts par défaut
defaults:
  - scope: { path: "" }
    values:
      layout: "page"
  - scope: { path: "", type: "posts" }
    values:
      layout: "post"
