# Exclusions
exclude:
  - README.md
  - node_modules

title: "Martial BODET • Freelance Talend & Power BI"
tagline: "Intégration de données, pipelines Talend, dashboards Power BI"
description: "Freelance Talend & Power BI : intégrations robustes, pipelines ETL, modélisation DAX, rapports interactifs. Interventions rapides, orientées résultats."
url: "https://username.github.io" # remplace si domaine custom
baseurl: "" # ne rien mettre pour username.github.io
lang: fr
timezone: Europe/Paris



theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Auteur (utilisé dans JSON-LD)
author:
  name: "Ton Nom"
  job_title: "Consultant Freelance Talend & Power BI"
  email: "contact@tondomaine.fr"
  url: "https://username.github.io"
  sameAs:
    - "https://www.linkedin.com/in/tonprofil/"
    - "https://github.com/username"


# Navigation du thème minima
minima:
  nav:
    - title: "Accueil"
      url: /
    - title: "Blog"
      url: /blog/
    - title: "Galerie"
      url: /gallery/
    - title: "Contact"
      url: /contact/ # crée la page plus tard si tu veux

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Layouts par défaut
defaults:
  - scope: { path: "" }
    values:
      layout: "page"
  - scope: { path: "", type: "posts" }
    values:
      layout: "post"
