# _config.yml
title: "LOCALUM - E2M"
brand: "LOCALUM - E2M"
logo_path: "/assets/logo.png" # remplacez par votre logo
description: "Location de jeux de lumière, sonorisation et packs DJ – installation possible – gironde et alentours."
url: "" # https://<user>.github.io (à compléter après déploiement)
baseurl: "" # laisser vide si à la racine

contact:
  phone: "+33 6 12 34 56 78"
  email: "contact@loclights.example"
  address: "12 rue des Fêtes, 33370 Espiet"
  siret: "123 456 789 00012"
  legal_contact: "Jean Exemple"

social:
  youtube: "https://youtube.com/@votre-chaine" # à remplacer

delivery:
  base_city: "Espiet"
  center_lat: 44.785
  center_lng: -0.265
  tiers:
    - { radius_km: 10, price_eur: 0,  label: "Zone 1" }
    - { radius_km: 25, price_eur: 20, label: "Zone 2" }
    - { radius_km: 50, price_eur: 45, label: "Zone 3" }
  install_price_from_eur: 49

forms:
  booking_google_form_url: "https://forms.gle/votre-form" # à remplacer

pricing:
  currency: "EUR"
  caution_policy: "Caution par chèque ou empreinte CB, restituée au retour du matériel."
  weekend: "Tarif week-end = retrait vendredi, retour lundi matin."
  notes: "Remises pour associations et étudiants sur justificatif."

seo:
  keywords: ["location sono", "location jeux de lumière", "DJ", "soirée", "mariage", "anniversaire", "Gironde", "Espiet"]
  city_targets: ["Espiet", "Bordeaux", "Libourne", "Entre-Deux-Mers", "Gironde"]
  open_graph_image: "/assets/og.jpg"
  enable_jsonld: true

theme: null
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md

permalink: /:title/
